import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
    try {
        const body = await request.json();
        const { caseData, format } = body;

        if (!caseData) {
            return NextResponse.json({ error: 'Case data is required' }, { status: 400 });
        }

        if (format === 'html') {
            return new NextResponse(generateHTMLReport(caseData), {
                headers: {
                    'Content-Type': 'text/html',
                    'Content-Disposition': `attachment; filename="DocuIntel_Report_${caseData.case_id || 'case'}.html"`,
                },
            });
        }

        return new NextResponse(generateTextReport(caseData), {
            headers: {
                'Content-Type': 'text/plain',
                'Content-Disposition': `attachment; filename="DocuIntel_Report_${caseData.case_id || 'case'}.txt"`,
            },
        });
    } catch (error: any) {
        return NextResponse.json({ error: 'Failed to generate report' }, { status: 500 });
    }
}

function generateTextReport(caseData: any): string {
    const summary = caseData.summary || {};
    const issues = caseData.reports?.executive_summary?.top_issues || [];
    const clauses = caseData.clauses || [];
    const risks = caseData.risks || [];
    const patches = caseData.redlines?.patches || [];

    let report = `DOCUINTEL - CONTRACT ANALYSIS REPORT\n`;
    report += `${'='.repeat(50)}\n\n`;
    report += `Document: ${caseData.title || 'Unknown'}\n`;
    report += `Case ID:  ${caseData.case_id || 'N/A'}\n`;
    report += `Date:     ${new Date().toLocaleDateString()}\n\n`;

    report += `RISK SUMMARY\n${'-'.repeat(30)}\n`;
    report += `Critical: ${summary.critical || 0}  |  High: ${summary.high || 0}  |  Medium: ${summary.medium || 0}  |  Low: ${summary.low || 0}\n`;
    report += `Total clauses analyzed: ${clauses.length}\n\n`;

    if (issues.length) {
        report += `KEY ISSUES\n${'-'.repeat(30)}\n`;
        issues.forEach((issue: string, i: number) => { report += `  ${i + 1}. ${issue}\n`; });
        report += '\n';
    }

    report += `CLAUSE-BY-CLAUSE ANALYSIS\n${'-'.repeat(30)}\n`;
    clauses.forEach((clause: any, i: number) => {
        const risk = risks.find((r: any) => r.clause_id === clause.clause_id);
        const patch = patches.find((p: any) => p.clause_id === clause.clause_id);
        report += `\n[${i + 1}] ${clause.heading || 'Clause'}\n`;
        report += `    Severity: ${(risk?.severity || 'low').toUpperCase()}\n`;
        report += `    Rationale: ${risk?.rationale || 'No issues detected'}\n`;
        if (patch?.patch) report += `    Suggested: ${patch.patch.slice(0, 200)}\n`;
    });

    report += `\n${'='.repeat(50)}\nGenerated by DocuIntel\n`;
    return report;
}

function generateHTMLReport(caseData: any): string {
    const summary = caseData.summary || {};
    const headline = caseData.reports?.executive_summary?.headline || 'Contract analysis complete.';
    const issues = caseData.reports?.executive_summary?.top_issues || [];
    const clauses = caseData.clauses || [];
    const risks = caseData.risks || [];
    const patches = caseData.redlines?.patches || [];
    const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

    const sevColor: Record<string, [string, string]> = {
        critical: ['#FEE2E2', '#DC2626'],
        high: ['#FEF3C7', '#D97706'],
        medium: ['#E0E7FF', '#4F46E5'],
        low: ['#D1FAE5', '#059669'],
    };

    const clauseRows = clauses.map((clause: any, i: number) => {
        const risk = risks.find((r: any) => r.clause_id === clause.clause_id);
        const patch = patches.find((p: any) => p.clause_id === clause.clause_id);
        const sev = risk?.severity || 'low';
        const [bg, fg] = sevColor[sev] || sevColor.low;

        return `
        <tr>
            <td style="padding:12px; border-bottom:1px solid #F3F4F6; font-size:13px; vertical-align:top;">
                <strong>${clause.heading || `Clause ${i + 1}`}</strong>
            </td>
            <td style="padding:12px; border-bottom:1px solid #F3F4F6; text-align:center; vertical-align:top;">
                <span style="background:${bg}; color:${fg}; padding:3px 10px; border-radius:20px; font-size:11px; font-weight:600; text-transform:uppercase;">${sev}</span>
            </td>
            <td style="padding:12px; border-bottom:1px solid #F3F4F6; font-size:12px; color:#4B5563; vertical-align:top;">
                ${risk?.rationale || 'No issues detected'}
            </td>
            <td style="padding:12px; border-bottom:1px solid #F3F4F6; font-size:12px; color:#2563EB; vertical-align:top;">
                ${patch?.patch ? patch.patch.slice(0, 150) + (patch.patch.length > 150 ? '...' : '') : '<span style="color:#9CA3AF;">None</span>'}
            </td>
        </tr>`;
    }).join('');

    const issueItems = issues.map((issue: string, i: number) =>
        `<li style="margin-bottom:8px; font-size:14px; color:#374151;">${issue}</li>`
    ).join('');

    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DocuIntel Report</title>
    <style>
        * { margin:0; padding:0; box-sizing:border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color:#111827; background:#fff; }
        .page { max-width:850px; margin:0 auto; padding:48px 40px; }
        .header { display:flex; justify-content:space-between; align-items:flex-start; padding-bottom:24px; border-bottom:3px solid #2563EB; margin-bottom:32px; }
        .logo { font-size:22px; font-weight:700; color:#2563EB; }
        .logo span { font-weight:400; color:#6B7280; }
        .meta { font-size:12px; color:#6B7280; text-align:right; line-height:1.6; }
        h2 { font-size:16px; color:#111827; margin:28px 0 12px; padding-bottom:6px; border-bottom:1px solid #E5E7EB; }
        .summary-text { font-size:15px; color:#374151; line-height:1.7; margin-bottom:24px; }
        .stats { display:flex; gap:12px; margin:20px 0 28px; }
        .stat { flex:1; padding:16px; border-radius:10px; text-align:center; }
        .stat-val { font-size:32px; font-weight:700; }
        .stat-label { font-size:10px; text-transform:uppercase; letter-spacing:0.05em; color:#6B7280; margin-top:4px; }
        table { width:100%; border-collapse:collapse; margin-top:12px; }
        th { background:#F9FAFB; padding:10px 12px; font-size:11px; text-transform:uppercase; letter-spacing:0.05em; color:#6B7280; text-align:left; border-bottom:2px solid #E5E7EB; }
        .footer { margin-top:40px; padding-top:16px; border-top:1px solid #E5E7EB; text-align:center; font-size:11px; color:#9CA3AF; }
        @media print { .page { padding:24px; } .stat-val { font-size:24px; } }
    </style>
</head>
<body>
<div class="page">
    <div class="header">
        <div>
            <div class="logo">DocuIntel <span>Legal AI</span></div>
            <div style="font-size:12px; color:#6B7280; margin-top:4px;">Contract Analysis Report</div>
        </div>
        <div class="meta">
            <div><strong>Document:</strong> ${caseData.title || 'Unknown Contract'}</div>
            <div><strong>Case ID:</strong> ${caseData.case_id || 'N/A'}</div>
            <div><strong>Generated:</strong> ${date}</div>
        </div>
    </div>

    <h2>Executive Summary</h2>
    <p class="summary-text">${headline}</p>

    <div class="stats">
        <div class="stat" style="background:#FEE2E2;"><div class="stat-val" style="color:#DC2626;">${summary.critical || 0}</div><div class="stat-label">Critical</div></div>
        <div class="stat" style="background:#FEF3C7;"><div class="stat-val" style="color:#D97706;">${summary.high || 0}</div><div class="stat-label">High</div></div>
        <div class="stat" style="background:#E0E7FF;"><div class="stat-val" style="color:#4F46E5;">${summary.medium || 0}</div><div class="stat-label">Medium</div></div>
        <div class="stat" style="background:#D1FAE5;"><div class="stat-val" style="color:#059669;">${summary.low || 0}</div><div class="stat-label">Low</div></div>
    </div>

    ${issues.length ? `<h2>Key Issues</h2><ol style="padding-left:20px; margin-top:8px;">${issueItems}</ol>` : ''}

    <h2>Clause Analysis</h2>
    <table>
        <thead>
            <tr>
                <th style="width:22%;">Clause</th>
                <th style="width:10%; text-align:center;">Risk</th>
                <th style="width:38%;">Rationale</th>
                <th style="width:30%;">Suggested Redline</th>
            </tr>
        </thead>
        <tbody>
            ${clauseRows}
        </tbody>
    </table>

    <div class="footer">
        Generated by DocuIntel Legal AI &middot; ${date} &middot; Confidential
    </div>
</div>
</body>
</html>`;
}
