import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
    try {
        const body = await request.json();
        const { caseData, format } = body;

        if (!caseData) {
            return NextResponse.json({ error: 'Case data is required' }, { status: 400 });
        }

        // HTML format for PDF-ready export (can be printed to PDF from browser)
        if (format === 'html') {
            return new NextResponse(generateHTMLReport(caseData), {
                headers: {
                    'Content-Type': 'text/html',
                    'Content-Disposition': `attachment; filename="DocuIntel_Report_${caseData.case_id || 'case'}.html"`,
                },
            });
        }

        // Default: plain text export
        const reportContent = generateTextReport(caseData);

        return new NextResponse(reportContent, {
            headers: {
                'Content-Type': 'text/plain',
                'Content-Disposition': `attachment; filename="DocuIntel_Report_${caseData.case_id || 'case'}.txt"`,
            },
        });
    } catch (error: any) {
        console.error('Report generation error:', error);
        return NextResponse.json({ error: 'Failed to generate report' }, { status: 500 });
    }
}

function generateTextReport(caseData: any): string {
    return `
DOCUINTEL LEGAL ANALYSIS REPORT
===============================
Case ID: ${caseData.case_id || 'N/A'}
Document: ${caseData.title || 'Unknown Contract'}
Date: ${new Date().toLocaleDateString()}

EXECUTIVE SUMMARY
-----------------
${caseData.reports?.executive_summary?.headline || 'Analysis summary not available.'}

RISK BREAKDOWN
--------------
Critical: ${caseData.summary?.critical || 0}
High: ${caseData.summary?.high || 0}
Medium: ${caseData.summary?.medium || 0}
Low: ${caseData.summary?.low || 0}

TOP ISSUES
----------
${(caseData.reports?.executive_summary?.top_issues || []).map((issue: string, i: number) => `${i + 1}. ${issue}`).join('\n')}

DETAILED CLAUSE ANALYSIS
------------------------
${(caseData.clauses || []).map((clause: any) => {
        const risk = caseData.risks?.find((r: any) => r.clause_id === clause.clause_id);
        const redline = caseData.redlines?.patches?.find((p: any) => p.clause_id === clause.clause_id);
        return `
---
Clause: ${(clause.heading || clause.text || '').substring(0, 100)}
Risk Level: ${risk?.severity?.toUpperCase() || 'UNKNOWN'}
Rationale: ${risk?.rationale || 'N/A'}
Proposed Redline: ${redline?.patch || 'No redline generated.'}
`;
    }).join('\n')}

Generated by DocuIntel
    `.trim();
}

function generateHTMLReport(caseData: any): string {
    const severityColor: Record<string, string> = {
        critical: '#EF4444',
        high: '#F59E0B',
        medium: '#EAB308',
        low: '#10B981',
    };

    const clauses = (caseData.clauses || []).map((clause: any) => {
        const risk = caseData.risks?.find((r: any) => r.clause_id === clause.clause_id);
        const redline = caseData.redlines?.patches?.find((p: any) => p.clause_id === clause.clause_id);
        const color = severityColor[risk?.severity] || '#6B7280';
        return `
        <div style="border:1px solid #e5e7eb; border-radius:8px; padding:16px; margin-bottom:12px;">
            <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:8px;">
                <strong>${clause.heading || (clause.text || '').substring(0, 60)}</strong>
                <span style="background:${color}20; color:${color}; padding:2px 10px; border-radius:12px; font-size:12px; font-weight:600; text-transform:uppercase;">${risk?.severity || 'unknown'}</span>
            </div>
            <p style="color:#6b7280; font-size:13px; margin-bottom:8px;">${risk?.rationale || ''}</p>
            ${redline?.patch ? `<p style="font-size:12px; color:#2563eb;"><strong>Suggested:</strong> ${redline.patch.substring(0, 200)}</p>` : ''}
        </div>`;
    }).join('');

    const issues = (caseData.reports?.executive_summary?.top_issues || [])
        .map((issue: string) => `<li style="margin-bottom:6px;">${issue}</li>`)
        .join('');

    return `<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>DocuIntel Report - ${caseData.case_id || 'Case'}</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #111827; }
        h1 { font-size: 24px; border-bottom: 2px solid #2563eb; padding-bottom: 8px; }
        h2 { font-size: 18px; color: #374151; margin-top: 32px; }
        .meta { color: #6b7280; font-size: 13px; margin-bottom: 24px; }
        .stats { display: flex; gap: 16px; margin: 16px 0; }
        .stat { padding: 12px 20px; border-radius: 8px; text-align: center; flex: 1; }
        .stat-val { font-size: 28px; font-weight: 700; }
        .stat-label { font-size: 11px; text-transform: uppercase; color: #6b7280; }
        @media print { body { padding: 20px; } }
    </style>
</head>
<body>
    <h1>Legal Analysis Report</h1>
    <div class="meta">
        <strong>Case:</strong> ${caseData.case_id || 'N/A'} |
        <strong>Document:</strong> ${caseData.title || 'Unknown'} |
        <strong>Date:</strong> ${new Date().toLocaleDateString()}
    </div>

    <h2>Executive Summary</h2>
    <p>${caseData.reports?.executive_summary?.headline || 'Analysis complete.'}</p>

    <div class="stats">
        <div class="stat" style="background:#FEF2F2;"><div class="stat-val" style="color:#EF4444;">${caseData.summary?.critical || 0}</div><div class="stat-label">Critical</div></div>
        <div class="stat" style="background:#FFFBEB;"><div class="stat-val" style="color:#F59E0B;">${caseData.summary?.high || 0}</div><div class="stat-label">High</div></div>
        <div class="stat" style="background:#FEF9C3;"><div class="stat-val" style="color:#EAB308;">${caseData.summary?.medium || 0}</div><div class="stat-label">Medium</div></div>
        <div class="stat" style="background:#ECFDF5;"><div class="stat-val" style="color:#10B981;">${caseData.summary?.low || 0}</div><div class="stat-label">Low</div></div>
    </div>

    ${issues ? `<h2>Key Issues</h2><ul>${issues}</ul>` : ''}

    <h2>Clause Analysis</h2>
    ${clauses}

    <hr style="margin-top:32px; border:none; border-top:1px solid #e5e7eb;">
    <p style="color:#9ca3af; font-size:11px; text-align:center; margin-top:16px;">Generated by DocuIntel</p>
</body>
</html>`;
}
